# Generated by Django 6.0.8 on 2026-09-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osivaultauditcheckpoint',
            name='previous_checkpoint_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='osivaultauditcheckpoint',
            name='row_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='osivaultauditcheckpoint',
            name='table_name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
